version: '3.9'

services:
  app:
    container_name: ${APP_CONTAINER}
    image: roalcantara/epokemons
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_CONTAINER}
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: ${DB_CONTAINER}
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USR}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: ${DB_CONTAINER_DATA}
    healthcheck:
      test: pg_isready -U ${DB_USR} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nodemodules: {}
  pgdata:
