version: '3.9'

services:
  app:
    container_name: ${APP_CONTAINER}
    image: roalcantara/epokemons
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    env_file:
      - .env
    environment:
      NODE_ENV: development
