version: '3.9'

services:
  app:
    container_name: ${APP_CONTAINER}
    image: roalcantara/epokemons
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_CONTAINER}
      EL_HOST: ${EL_CONTAINER}
    links:
      - postgres
      - elasticsearch
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    container_name: ${DB_CONTAINER}
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./tools/scripts/sql:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USR}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: ${DB_CONTAINER_DATA}
    healthcheck:
      test: pg_isready -U ${DB_USR} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
    container_name: ${EL_CONTAINER}
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - ${EL_PORT}:${EL_PORT}
    expose:
      - ${EL_PORT}
    environment:
      node.name: ${EL_CONTAINER}
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - eldata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -f '${EL_HOST}:${EL_PORT}' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nodemodules: {}
  pgdata:
  eldata:
